### ISSUE TITLE
0.4.0 feature list

### ISSUE THREAD

**Issue by dirkraft** [blacklocus/metrics-cloudwatch#15]
PR: coming....

Internal needs justify spending some time on metrics-cloudwatch. Targeting the following enhancements:

  - [x] 1) configurable metric type dimension (#10 talks about this too).
    * Currently type=[gauge, counterSum, meterSum, histogramCount, histogramSet, timerCount, timerSet]
    * Will become metricType=[gauge, counterCount, meterCount, histoSamples, histoStats, timerSamples, timerStats] which better describe what is being translated from code hale metric classes to cloudwatch
    * All of these strings will be configurable, in case you want an even less confusing metric type identifier, or you have conflicting dimensions.

  - [x] 2) better defaults of metric type dimension values where the user does not explicitly configure the names in the previous bullet point. e.g. "histogramCount" -> "histogramSamples" because the coda hale Histogram.getCount actually returns the number of samples, not the sum of values. This is unlike a plain Counter where .getCount actually returns the sum of all values.

  - [x] 3) a general update of all dependency versions

  - [x] 4) CloudWatchReporterBuilder fluent style builder for CloudWatchReporter which will use the new default values

   * [x] *Should* be backwards compatible with the last version of CloudWatchReporter. Making a best effort here to not rename or remove any existing signatures. Constructing the CloudWatchReporter directly will use all of the **old** metric type dimensions; the CloudWatchReporterBuilder will use the new defaults. Backwards-compatibility excludes any effects of 3) transitive dependency updates (and any resulting transitive dependency conflicts)

  - [x] 5) A pass over README.md and all java-doc for accuracy clarity

  - [x] 6) make submission of 0 values configurable #14 

  - [x] 7) try to guard against "Value of 0 is invalid" #13

  - [x] 8) option to set date on metrics explicitly to now (new Date()) or leave null (cloudwatch timestamps it on receipt)

**Comment by dirkraft** [comment]
I'm satisfied for now

**Comment by dirkraft** [comment]
Calling out that 6) and 7) were not exactly implemented after all.

**Comment by vinaygurram** [comment]
Hi,
I am using this and https://github.com/jdamick/dropwizard-metrics-cloudwatch to send metrics. 

> InvalidParameterValueException: The value 0 for parameter MetricData.member.11.Value is invalid.
> is killing my logs. 

How can I use this reported filter ?.

Things I found out : 
https://github.com/jdamick/dropwizard-metrics-cloudwatch is using the following constructor to get reporter. 
CloudWatchReporter(registry, metricNamespace, metricFilter, cloudWatch) 

Thanks,
Vinay

**Comment by kamalvpm777** [comment]
Hello,
we are also facing similar error when posting the very small number(4.784335455263847e-50,) to cloudwatch from telegraf dropwizard metrics. Any suggestion on how to fix this error will be greatly appreciated.

2017-03-14T19:09:06Z E! Error writing to output [cloudwatch]: InvalidParameterValue: The value 0 for parameter MetricData.member.14.Value is invalid.
2017-03-14T19:09:20Z D! Output [cloudwatch] buffer fullness: 223 / 10000 metrics. 
2017-03-14T19:09:26Z E! CloudWatch: Unable to write to CloudWatch : InvalidParameterValue: The value 0 for parameter MetricData.member.6.Value is invalid.
2017-03-14T19:09:26Z E! Error writing to output [cloudwatch]: InvalidParameterValue: The value 0 for parameter MetricData.member.6.Value is invalid.
